for i in range(1):
    print("Lexicogenesis")
    print("-creacion original")
    print("-via externa:")
    print("   prestamo:")
    print("     -de xenismo a calco")
    print("     -xenismo: palabra exactamente igual, fonica y visualmente, al idioma extranejero")
    print("     -calco: totalmente incorporado al castellano")
    print("     -calco semantico: es uan traduccion literal")
    print("-via interna:")
    print("   derivacion:")
    print("     -sufijacion: nacion > nacionalizar")
    print("     -prefijacion: legal > ilegal")
    print("     -circunfijacion: papel > empapelar")
    print("     -reegresiva: debatir > debate")
    print("  composicion:")
    print("     -por modelo: por ejemplo verdo + sustantivo: sacacorchos")
    print("     -por inmovilizacion o locucion: por ejemplo: meter la pata")
    print("  confijacion:")
    print("     -confijo, no tiene posicion fija, se usa para raices clasicas. ej.: biblio+teca > biblioteca")
    print("  parasintesis:")
    print("     -cuando la historia de la palabra es opaca y la estructura es raiz + raiz + afijo. ej.: quinceanero")
    print("  acortamiento o reduccion:")
    print("     -apocope: mantiene el principio")
    print("     -aferesis: mantiene el final")
    print("  acronimos: unidad liberable + unidad liberable, y se acorta una o las dos")
    print("  hipocoristicos: nombres propios abreviados")
    print("Clasificacion de palabras")
    print("-heterogenea: al cambiar la palabra, su categoria gramatical cambia")
    print("-homogenea: al cambiar la palabra, su categoria gramatical no cambia")
    print("-apreciativa: cambia el sentido connotativo")
